# -*- coding: utf-8 -*-
"""
Script to enrich all 550 Thai vocabulary words with exact English translations.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

english_map = {
    # อาหารและเครื่องดื่ม (Food)
    "กะเพรา": "Holy Basil",
    "ก๋วยเตี๋ยว": "Noodles",
    "ต้มยำ": "Tom Yum Soup",
    "มะม่วง": "Mango",
    "ทุเรียน": "Durian",
    "ส้มตำ": "Papaya Salad",
    "น้ำพริก": "Chili Paste",
    "ชาเขียว": "Green Tea",
    "ข้าวมันไก่": "Hainanese Chicken Rice",
    "ข้าวซอย": "Khao Soi (Northern Curry Noodles)",
    "แกงเขียวหวาน": "Green Curry",
    "พะแนง": "Panang Curry",
    "ผัดไทย": "Pad Thai",
    "มัสมั่น": "Massaman Curry",
    "ทอดมัน": "Fried Fish Cakes",
    "ไข่เจียว": "Thai Omelet",
    "ต้มข่าไก่": "Chicken Coconut Soup",
    "หมูกระทะ": "Thai BBQ & Hotpot",
    "ปลากะพง": "Asian Sea Bass",
    "หอยนางรม": "Oyster",
    "กุ้งเผา": "Grilled River Prawn",
    "กาแฟ": "Coffee",
    "นมสด": "Fresh Milk",
    "น้ำเต้าหู้": "Soy Milk",
    "ลอดช่อง": "Pandan Cendol in Coconut Milk",
    "บัวลอย": "Rice Balls in Sweet Coconut Milk",
    "ขนมครก": "Coconut Rice Pancakes",
    "ข้าวต้ม": "Rice Soup / Porridge",
    "โจ๊ก": "Congee",
    "กวยจั๊บ": "Rolled Rice Noodle Soup",
    "ซาลาเปา": "Steamed Bun (Baozi)",
    "เกี๊ยวซ่า": "Gyoza (Dumpling)",
    "โรตี": "Roti",
    "แตงโม": "Watermelon",
    "สับปะรด": "Pineapple",
    "เงาะ": "Rambutan",
    "มังคุด": "Mangosteen",
    "ลำไย": "Longan",
    "ฝรั่ง": "Guava",
    "ส้มโอ": "Pomelo",
    "กล้วยหอม": "Cavendish Banana",
    "มะพร้าว": "Coconut",
    "ขนุน": "Jackfruit",
    "มะละกอ": "Papaya",
    "ชมพู่": "Rose Apple",
    "แก้วมังกร": "Dragon Fruit",
    "ลองกอง": "Longkong",
    "กระเทียม": "Garlic",
    "หอมแดง": "Shallot",
    "ตะไคร้": "Lemongrass",
    "ข่า": "Galangal",
    "ใบมะกรูด": "Kaffir Lime Leaves",
    "มะนาว": "Lime",
    "พริกขี้หนู": "Bird's Eye Chili",
    "น้ำปลา": "Fish Sauce",
    "ซีอิ๊ว": "Soy Sauce",
    "กะปิ": "Shrimp Paste",
    "น้ำตาลปี๊บ": "Palm Sugar",
    "ขมิ้น": "Turmeric",
    "กะทิ": "Coconut Milk",

    # สัตว์และธรรมชาติ (Animals & Nature)
    "ช้าง": "Elephant",
    "ม้า": "Horse",
    "วัว": "Cow",
    "ควาย": "Water Buffalo",
    "เสือ": "Tiger",
    "สิงโต": "Lion",
    "หมี": "Bear",
    "ลิง": "Monkey",
    "กระรอก": "Squirrel",
    "กระต่าย": "Rabbit",
    "กวาง": "Deer",
    "สุนัข": "Dog",
    "แมว": "Cat",
    "นกพิราบ": "Pigeon",
    "นกยูง": "Peacock",
    "นกฮูก": "Owl",
    "เหยี่ยว": "Hawk",
    "เป็ด": "Duck",
    "ไก่": "Chicken",
    "ห่าน": "Goose",
    "ปลาทอง": "Goldfish",
    "ปลาวาฬ": "Whale",
    "โลมา": "Dolphin",
    "ฉลาม": "Shark",
    "เต่า": "Turtle",
    "จระเข้": "Crocodile",
    "กบ": "Frog",
    "อึ่งอ่าง": "Bullfrog",
    "ผีเสื้อ": "Butterfly",
    "ผึ้ง": "Bee",
    "มด": "Ant",
    "ปลวก": "Termite",
    "แมลงปอ": "Dragonfly",
    "หิ่งห้อย": "Firefly",
    "ยุง": "Mosquito",
    "ภูเขา": "Mountain",
    "น้ำตก": "Waterfall",
    "ทะเล": "Sea",
    "มหาสมุทร": "Ocean",
    "เกาะ": "Island",
    "หาดทราย": "Sandy Beach",
    "ถ้ำ": "Cave",
    "แม่น้ำ": "River",
    "ลำธาร": "Stream",
    "คลอง": "Canal",
    "ป่าดงดิบ": "Rainforest",
    "พระอาทิตย์": "Sun",
    "พระจันทร์": "Moon",
    "ดวงดาว": "Star",
    "ก้อนเมฆ": "Cloud",
    "สายรุ้ง": "Rainbow",
    "ฝนตก": "Rain",
    "พายุ": "Storm",
    "ฟ้าร้อง": "Thunder",
    "ฟ้าผ่า": "Lightning",
    "ดอกบัว": "Lotus",
    "ดอกมะลิ": "Jasmine",
    "ดอกกล้วยไม้": "Orchid",
    "ดอกกุหลาบ": "Rose",
    "ต้นไทร": "Banyan Tree",

    # ร่างกายและสุขภาพ (Body & Health)
    "ศีรษะ": "Head",
    "ใบหน้า": "Face",
    "ดวงตา": "Eye",
    "คิ้ว": "Eyebrow",
    "ขนตา": "Eyelash",
    "หู": "Ear",
    "จมูก": "Nose",
    "ริมฝีปาก": "Lips",
    "ฟัน": "Tooth / Teeth",
    "ลิ้น": "Tongue",
    "คาง": "Chin",
    "ลำคอ": "Neck / Throat",
    "หัวไหล่": "Shoulder",
    "แขน": "Arm",
    "ข้อศอก": "Elbow",
    "ข้อมือ": "Wrist",
    "มือ": "Hand",
    "นิ้วมือ": "Finger",
    "เล็บ": "Nail",
    "หน้าอก": "Chest",
    "ท้อง": "Belly / Stomach",
    "หัวใจ": "Heart",
    "ปอด": "Lung",
    "ตับ": "Liver",
    "ไต": "Kidney",
    "กระเพาะ": "Stomach",
    "ลำไส้": "Intestines",
    "กระดูก": "Bone",
    "กล้ามเนื้อ": "Muscle",
    "เส้นประสาท": "Nerve",
    "เลือด": "Blood",
    "ผิวหนัง": "Skin",
    "สุขภาพ": "Health",
    "แข็งแรง": "Strong / Healthy",
    "ออกกำลังกาย": "Exercise",
    "วิตามิน": "Vitamin",
    "บาดเจ็บ": "Injured",
    "ไข้หวัด": "Cold / Flu",
    "ไอ": "Cough",
    "จาม": "Sneeze",
    "ปวดหัว": "Headache",
    "ปวดท้อง": "Stomachache",
    "คลื่นไส้": "Nausea",
    "เวียนศีรษะ": "Dizziness",
    "อักเสบ": "Inflamed",
    "ติดเชื้อ": "Infected",
    "ภูมิแพ้": "Allergy",
    "พยาบาล": "Nurse",
    "แพทย์": "Doctor / Physician",
    "ยารักษาโรค": "Medicine",
    "โรงพยาบาล": "Hospital",
    "คลินิก": "Clinic",
    "วัคซีน": "Vaccine",
    "พักผ่อน": "Rest",
    "รอยยิ้ม": "Smile",
    "ความดัน": "Blood Pressure",
    "ชีพจร": "Pulse",
    "สายตา": "Eyesight",
    "หายใจ": "Breathe",
    "สมอง": "Brain",

    # ชีวิตประจำวันและสิ่งของ (Daily Life)
    "ตื่นนอน": "Wake up",
    "ล้างหน้า": "Wash face",
    "แปรงฟัน": "Brush teeth",
    "อาบน้ำ": "Take a shower",
    "แต่งตัว": "Get dressed",
    "รับประทาน": "Eat / Dine",
    "อ่านหนังสือ": "Read a book",
    "ทำการบ้าน": "Do homework",
    "ทำงาน": "Work",
    "เข้านอน": "Go to bed",
    "หลับฝัน": "Dream",
    "นาฬิกา": "Clock / Watch",
    "ปฏิทิน": "Calendar",
    "กระเป๋า": "Bag",
    "รองเท้า": "Shoes",
    "ถุงเท้า": "Socks",
    "เสื้อผ้า": "Clothes",
    "กางเกง": "Pants / Trousers",
    "หมวก": "Hat / Cap",
    "แว่นตา": "Glasses",
    "ร่ม": "Umbrella",
    "ผ้าเช็ดตัว": "Towel",
    "สบู่": "Soap",
    "ยาสระผม": "Shampoo",
    "ยาสีฟัน": "Toothpaste",
    "หวี": "Comb",
    "กระจก": "Mirror",
    "เตียงนอน": "Bed",
    "หมอน": "Pillow",
    "ผ้าห่ม": "Blanket",
    "โต๊ะ": "Table / Desk",
    "เก้าอี้": "Chair",
    "โซฟา": "Sofa",
    "ประตู": "Door",
    "หน้าต่าง": "Window",
    "กุญแจ": "Key",
    "โคมไฟ": "Lamp",
    "พัดลม": "Fan",
    "เครื่องปรับอากาศ": "Air Conditioner",
    "ตู้เย็น": "Refrigerator",
    "ไมโครเวฟ": "Microwave",
    "โทรทัศน์": "Television",
    "โทรศัพท์": "Telephone / Phone",
    "คอมพิวเตอร์": "Computer",
    "หูฟัง": "Headphones",
    "ปากกา": "Pen",
    "ดินสอ": "Pencil",
    "ยางลบ": "Eraser",
    "ไม้บรรทัด": "Ruler",
    "สมุด": "Notebook",
    "กรรไกร": "Scissors",
    "กาว": "Glue",
    "กระดาษ": "Paper",
    "จาน": "Plate",
    "ชาม": "Bowl",
    "ช้อน": "Spoon",
    "ส้อม": "Fork",
    "แก้วน้ำ": "Drinking Glass",
    "ทำความสะอาด": "Clean up",
    "จัดระเบียบ": "Organize",

    # การเดินทางและสถานที่ (Travel & Places)
    "รถยนต์": "Car / Automobile",
    "รถจักรยานยนต์": "Motorcycle",
    "รถจักรยาน": "Bicycle",
    "รถโดยสาร": "Bus",
    "รถไฟฟ้า": "Skytrain (BTS)",
    "รถไฟใต้ดิน": "Subway (MRT)",
    "รถไฟ": "Train",
    "เรือหางยาว": "Long-tail Boat",
    "เรือสำราญ": "Cruise Ship",
    "เครื่องบิน": "Airplane",
    "เฮลิคอปเตอร์": "Helicopter",
    "ท่าอากาศยาน": "Airport",
    "สถานีรถไฟ": "Train Station",
    "ท่าเรือ": "Pier / Harbor",
    "ป้ายรถเมล์": "Bus Stop",
    "ทางด่วน": "Expressway",
    "สะพาน": "Bridge",
    "อุโมงค์": "Tunnel",
    "สี่แยก": "Intersection",
    "ทางม้าลาย": "Zebra Crossing",
    "ทางเท้า": "Sidewalk / Pavement",
    "สัญญาณไฟ": "Traffic Light",
    "ตั๋วเดินทาง": "Travel Ticket",
    "หนังสือเดินทาง": "Passport",
    "โรงแรม": "Hotel",
    "ที่พัก": "Accommodation",
    "รีสอร์ต": "Resort",
    "ชายหาด": "Beach",
    "จุดชมวิว": "Viewpoint",
    "วัด": "Temple",
    "โบสถ์": "Church / Chapel",
    "มัสยิด": "Mosque",
    "พิพิธภัณฑ์": "Museum",
    "หอศิลป์": "Art Gallery",
    "สวนสัตว์": "Zoo",
    "สวนสนุก": "Amusement Park",
    "สวนสาธารณะ": "Public Park",
    "ตลาด": "Market",
    "ซูเปอร์มาร์เก็ต": "Supermarket",
    "ห้างสรรพสินค้า": "Department Store",
    "ธนาคาร": "Bank",
    "ที่ทำการไปรษณีย์": "Post Office",
    "สถานีตำรวจ": "Police Station",
    "ดับเพลิง": "Fire Station",
    "ร้านอาหาร": "Restaurant",
    "ร้านกาแฟ": "Cafe / Coffee Shop",
    "ห้องสมุด": "Library",
    "โรงภาพยนตร์": "Cinema / Movie Theater",
    "สนามกีฬา": "Stadium",
    "สถานทูต": "Embassy",
    "ศาลากลาง": "City Hall / Provincial Hall",
    "แผนที่": "Map",
    "เข็มทิศ": "Compass",
    "กระเป๋าเดินทาง": "Luggage / Suitcase",
    "เช็คอิน": "Check-in",
    "ออกเดินทาง": "Depart",
    "ถึงที่หมาย": "Arrive",
    "ท่องเที่ยว": "Travel / Tour",
    "นักท่องเที่ยว": "Tourist",
    "มัคคุเทศก์": "Tour Guide",

    # อารมณ์และความรู้สึก (Emotions)
    "มีความสุข": "Happy",
    "ดีใจ": "Glad / Delighted",
    "ร่าเริง": "Cheerful",
    "เพลิดเพลิน": "Enjoyable",
    "เบิกบาน": "Joyful",
    "หัวเราะ": "Laugh",
    "สบายใจ": "At ease / Relieved",
    "อบอุ่น": "Warm",
    "สงบสุข": "Peaceful",
    "ตื่นเต้น": "Excited",
    "ประทับใจ": "Impressed",
    "ภาคภูมิใจ": "Proud",
    "มั่นใจ": "Confident",
    "ศรัทธา": "Faith",
    "กตัญญู": "Grateful",
    "เมตตา": "Loving-kindness",
    "กรุณา": "Compassion",
    "เสียสละ": "Sacrifice",
    "ซื่อสัตย์": "Honest",
    "เกรงใจ": "Considerate",
    "อ่อนน้อม": "Humble",
    "โอบอ้อมอารี": "Generous",
    "เห็นอกเห็นใจ": "Empathetic",
    "เสียใจ": "Sad / Sorry",
    "ร้องไห้": "Cry",
    "โศกเศร้า": "Sorrowful",
    "เหงา": "Lonely",
    "ผิดหวัง": "Disappointed",
    "เสียดาย": "Regretful",
    "ท้อแท้": "Discouraged",
    "โกรธ": "Angry",
    "โมโห": "Furious",
    "หงุดหงิด": "Irritated",
    "ขุ่นเคือง": "Resentful",
    "อิจฉา": "Jealous / Envious",
    "หึงหวง": "Possessive",
    "หวาดกลัว": "Scared / Fearful",
    "ตกใจ": "Shocked",
    "กังวล": "Worried",
    "หวาดระแวง": "Suspicious",
    "เครียด": "Stressed",
    "เหน็ดเหนื่อย": "Tired / Exhausted",
    "อ่อนเพลีย": "Fatigued / Weak",
    "เบื่อหน่าย": "Bored",
    "สับสน": "Confused",
    "ลังเล": "Hesitant",
    "ประหม่า": "Nervous",
    "เขินอาย": "Shy",
    "อัศจรรย์ใจ": "Amazed",
    "ประหลาดใจ": "Surprised",
    "ซาบซึ้ง": "Deeply touched",
    "ห่วงใย": "Caring",
    "คิดถึง": "Miss / Think of",
    "ปลอดภัย": "Safe",
    "ไว้ใจ": "Trust",
    "จริงใจ": "Sincere",
    "อดทน": "Patient / Enduring",
    "พยายาม": "Strive / Try",
    "ตั้งใจ": "Determined",
    "หวังดี": "Well-meaning",

    # อาชีพและการทำงาน (Jobs & Work)
    "คุณครู": "Teacher",
    "อาจารย์": "Professor / Lecturer",
    "นักเรียน": "School Student",
    "นักศึกษา": "University Student",
    "แพทย์": "Doctor / Physician",
    "ทันตแพทย์": "Dentist",
    "เภสัชกร": "Pharmacist",
    "พยาบาล": "Nurse",
    "สัตวแพทย์": "Veterinarian",
    "วิศวกร": "Engineer",
    "สถาปนิก": "Architect",
    "ช่างไม้": "Carpenter",
    "ช่างไฟ": "Electrician",
    "ช่างประปา": "Plumber",
    "ช่างก่อสร้าง": "Construction Worker",
    "นักบิน": "Pilot",
    "แอร์โฮสเตส": "Flight Attendant",
    "กัปตันเรือ": "Ship Captain",
    "คนขับรถ": "Driver",
    "ตำรวจ": "Police Officer",
    "ทหาร": "Soldier",
    "นักดับเพลิง": "Firefighter",
    "ทนายความ": "Lawyer / Attorney",
    "ผู้พิพากษา": "Judge",
    "อัยการ": "Public Prosecutor",
    "นักการทูต": "Diplomat",
    "นักการเมือง": "Politician",
    "พ่อค้า": "Merchant (Male)",
    "แม่ค้า": "Merchant (Female)",
    "นักธุรกิจ": "Businessperson",
    "ผู้จัดการ": "Manager",
    "พนักงานบัญชี": "Accountant",
    "เลขานุการ": "Secretary",
    "โปรแกรมเมอร์": "Programmer / Developer",
    "นักออกแบบ": "Designer",
    "ช่างภาพ": "Photographer",
    "ศิลปิน": "Artist",
    "นักดนตรี": "Musician",
    "นักร้อง": "Singer",
    "นักแสดง": "Actor / Actress",
    "ผู้กำกับ": "Film Director",
    "นักเขียน": "Writer / Author",
    "นักข่าว": "Journalist / Reporter",
    "บรรณาธิการ": "Editor",
    "ล่าม": "Interpreter",
    "นักแปล": "Translator",
    "พ่อครัว": "Chef / Cook",
    "บริกร": "Waiter / Waitress",
    "บาริสต้า": "Barista",
    "เกษตรกร": "Agriculturist / Farmer",
    "ชาวนา": "Rice Farmer",
    "ชาวสวน": "Gardener / Orchardist",
    "ชาวประมง": "Fisherman",
    "นักวิทยาศาสตร์": "Scientist",
    "นักวิจัย": "Researcher",
    "นักโบราณคดี": "Archaeologist",
    "นักบินอวกาศ": "Astronaut",
    "นักกีฬา": "Athlete",
    "ผู้ฝึกสอน": "Coach / Trainer",
    "จิตอาสา": "Volunteer",

    # การศึกษาและวิทยาการ (Education & Science)
    "โรงเรียน": "School",
    "มหาวิทยาลัย": "University",
    "ห้องเรียน": "Classroom",
    "ห้องทดลอง": "Laboratory",
    "การศึกษา": "Education",
    "ปัญญา": "Wisdom",
    "ความรู้": "Knowledge",
    "บทเรียน": "Lesson",
    "ตำรา": "Textbook",
    "วิทยานิพนธ์": "Thesis / Dissertation",
    "ข้อสอบ": "Examination / Test",
    "การสอบ": "Exam",
    "คะแนน": "Score / Marks",
    "ประกาศนียบัตร": "Certificate",
    "ปริญญาบัตร": "Degree Diploma",
    "ภาษาศาสตร์": "Linguistics",
    "วรรณคดี": "Literature",
    "ประวัติศาสตร์": "History",
    "ภูมิศาสตร์": "Geography",
    "คณิตศาสตร์": "Mathematics",
    "วิทยาศาสตร์": "Science",
    "ฟิสิกส์": "Physics",
    "เคมี": "Chemistry",
    "ชีววิทยา": "Biology",
    "ดาราศาสตร์": "Astronomy",
    "สิ่งแวดล้อม": "Environment",
    "เทคโนโลยี": "Technology",
    "นวัตกรรม": "Innovation",
    "จินตนาการ": "Imagination",
    "ความคิดสร้างสรรค์": "Creativity",
    "การทดลอง": "Experiment",
    "สมมติฐาน": "Hypothesis",
    "ทฤษฎี": "Theory",
    "บทสรุป": "Conclusion",
    "สถิติ": "Statistics",
    "ข้อมูล": "Data / Information",
    "ประดิษฐ์": "Invent",
    "ค้นคว้า": "Research / Explore",
    "วิจัย": "Research",

    # พระพุทธศาสนาและพระสงฆ์ (Buddhism)
    "พระภิกษุ": "Buddhist Monk",
    "สามเณร": "Novice Monk",
    "อุปสมบท": "Higher Ordination (Monkhood)",
    "บรรพชา": "Novice Ordination",
    "บิณฑบาต": "Alms Round (Bhiksha)",
    "จีวร": "Monk's Robe (Civara)",
    "สบง": "Monk's Undergarment (Antaravasaka)",
    "สังฆาฏิ": "Shoulder Cloth (Sanghati)",
    "บาตร": "Monk's Alms Bowl",
    "กุฏิ": "Monk's Dwelling / Cell (Kuti)",
    "จำวัด": "Sleep (Monastic)",
    "ภัตตาหาร": "Monk's Meal (Food)",
    "ฉัน": "Eat / Consume (Monastic)",
    "ประเคน": "Hand over offerings to a monk",
    "อาพาธ": "Sick / Ill (Monastic)",
    "มรณภาพ": "Pass away / Die (Monastic)",
    "ปลงผม": "Shave Head (for ordination)",
    "สวดมนต์": "Chant / Prayer",
    "พระรัตนตรัย": "The Triple Gem (Three Jewels)",
    "พระพุทธเจ้า": "The Lord Buddha",
    "พระธรรม": "The Dhamma (Buddha's Teachings)",
    "พระสงฆ์": "The Sangha (Monastic Order)",
    "ไตรปิฎก": "Tripitaka (Pali Canon)",
    "ศีล": "Precepts / Morality (Sila)",
    "สมาธิ": "Meditation / Concentration (Samadhi)",
    "อริยสัจ": "Four Noble Truths",
    "นิพพาน": "Nirvana (Enlightenment)",
    "ทำบุญ": "Make Merit (Punya)",
    "ตักบาตร": "Put Food in Monk's Alms Bowl",
    "กรวดน้ำ": "Pour Water of Dedication",
    "เวียนเทียน": "Candlelit Procession",
    "อนุโมทนา": "Rejoice in Others' Merits",
    "สังฆทาน": "Offerings Dedicated to the Sangha",
    "กฐิน": "Kathina Robe Offering Ceremony",
    "ผ้าป่า": "Pha Pa (Forest Robe Offering)",
    "ปัจจัย": "Monastic Requisites / Donations",
    "อุโบสถ": "Ordination Hall (Ubosot)",
    "วิหาร": "Assembly Hall (Vihara)",
    "เจดีย์": "Stupa / Pagoda / Chedi",
    "ธรรมาสน์": "Preaching Pulpit",
    "เทศนา": "Deliver a Sermon",
    "วิปัสสนา": "Vipassana (Insight Meditation)",
    "อาสนะ": "Monk's Sitting Mat",
    "พรรษา": "Vassa (Rains Retreat / Years of Monkhood)",
    "จำพรรษา": "Observe the Rains Retreat",
    "สมณสารูป": "Monastic Decorum",
    "เจริญพระพุทธมนต์": "Chant Protective Verses (Paritta)",
    "ศาลาการเปรียญ": "Preaching Hall (Sala)",
    "สาธุ": "Sadhu (Well said / Amen)",

    # คำน่ารู้และสำนวนไทย (Tricky Words & Proverbs)
    "กาลเทศะ": "Propriety / Good Manners for the Occasion",
    "มโนภาพ": "Mental Image / Visualization",
    "อัศจรรย์": "Miraculous / Marvelous",
    "ปรากฏ": "Appear / Manifest",
    "อนุญาต": "Permit / Allow",
    "สังเกต": "Observe / Notice",
    "รสชาติ": "Taste / Flavor",
    "สัปดาห์": "Week",
    "บรรยากาศ": "Atmosphere / Ambiance",
    "กิจการ": "Business / Enterprise",
    "โอกาส": "Opportunity / Chance",
    "อากาศ": "Weather / Air",
    "มารยาท": "Manners / Etiquette",
    "ปาฏิหาริย์": "Miracle",
    "พรรณนา": "Describe in detail / Depict",
    "วิจิตร": "Exquisite / Ornate",
    "ทัศนียภาพ": "Scenery / Landscape",
    "ปรารถนา": "Wish / Desire",
    "วัฒนธรรม": "Culture",
    "ประเพณี": "Tradition / Custom",
    "เอกลักษณ์": "Identity / Uniqueness",
    "สัมพันธภาพ": "Relationship / Rapport",
    "อัธยาศัย": "Hospitality / Friendliness",
    "ประสบการณ์": "Experience",
    "ทัศนคติ": "Attitude / Perspective",
    "ประสิทธิภาพ": "Efficiency / Effectiveness",
    "สุภาษิต": "Proverb / Maxim",
    "น้ำขึ้นให้รีบตัก": "Make hay while the sun shines",
    "ไก่งามเพราะขน": "Clothes make the man",
    "เข้าเมืองตาหลิ่ว": "When in Rome, do as the Romans do",
    "น้ำพึ่งเรือเสือพึ่งป่า": "Mutual interdependence",
    "ช้าๆได้พร้าสองเล่มงาม": "Slow and steady wins the race",
    "รู้ไว้ใช่ว่า": "Knowledge is never a burden",
    "ปากหวานก้นเปรี้ยว": "Sweet tongue, bitter heart (Hypocritical)",
    "วัวหายล้อมคอก": "Lock the barn door after the horse is stolen",
    "ชี้โพรงให้กระรอก": "Give someone bad ideas unintentionally",
    "จับปลาสองมือ": "Try to catch two fish at once (Divided attention)",
    "กบในกะลาครอบ": "A frog under a coconut shell (Narrow-minded)",
    "เอาใจใส่": "Attentive / Caring",
    "ซื่อสัตย์สุจริต": "Integrity / Upright Honesty"
}

# Load current words.js
with open(r"c:\Users\beelink\Desktop\Ai actions\AntiGravity\news\thai-vocab-app\words.js", "r", encoding="utf-8") as f:
    content = f.read()

# Extract json
cat_marker = "const INITIAL_CATEGORIES = "
word_marker = "const INITIAL_WORDS = "

cat_start = content.find(cat_marker) + len(cat_marker)
cat_end = content.find(";\n\nconst INITIAL_WORDS")
categories = json.loads(content[cat_start:cat_end].strip())

word_start = content.find(word_marker) + len(word_marker)
words = json.loads(content[word_start:].strip().rstrip(';'))

# Enrich with english
matched = 0
for w in words:
    th_word = w["word"]
    if th_word in english_map:
        w["english"] = english_map[th_word]
        matched += 1
    else:
        w["english"] = w.get("romanization", "")

print(f"Total words: {len(words)}, Successfully matched English: {matched}")

# Rebuild words.js
new_content = f"""// คลังคำศัพท์ภาษาไทย 550 คำแบ่งตาม 10 หมวดหมู่ (Thai Vocabulary Dataset with English Translations)
// ออกแบบมาเพื่อการเรียนรู้ การออกเสียง และการฝึกทบทวนบนแท็บเล็ตและคอมพิวเตอร์

const INITIAL_CATEGORIES = {json.dumps(categories, ensure_ascii=False, indent=2)};

const INITIAL_WORDS = {json.dumps(words, ensure_ascii=False, indent=2)};
"""

with open(r"c:\Users\beelink\Desktop\Ai actions\AntiGravity\news\thai-vocab-app\words.js", "w", encoding="utf-8") as f:
    f.write(new_content)

print("Updated words.js with English translations successfully!")
